// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: proto/alfred.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Alfred_LoadImage_FullMethodName   = "/proto.Alfred/LoadImage"
	Alfred_ScheduleJob_FullMethodName = "/proto.Alfred/ScheduleJob"
	Alfred_Ping_FullMethodName        = "/proto.Alfred/Ping"
)

// AlfredClient is the client API for Alfred service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlfredClient interface {
	LoadImage(ctx context.Context, opts ...grpc.CallOption) (Alfred_LoadImageClient, error)
	ScheduleJob(ctx context.Context, in *ScheduleJobRequest, opts ...grpc.CallOption) (*ScheduleJobResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type alfredClient struct {
	cc grpc.ClientConnInterface
}

func NewAlfredClient(cc grpc.ClientConnInterface) AlfredClient {
	return &alfredClient{cc}
}

func (c *alfredClient) LoadImage(ctx context.Context, opts ...grpc.CallOption) (Alfred_LoadImageClient, error) {
	stream, err := c.cc.NewStream(ctx, &Alfred_ServiceDesc.Streams[0], Alfred_LoadImage_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &alfredLoadImageClient{stream}
	return x, nil
}

type Alfred_LoadImageClient interface {
	Send(*LoadImageMessage) error
	Recv() (*LoadImageResponse, error)
	grpc.ClientStream
}

type alfredLoadImageClient struct {
	grpc.ClientStream
}

func (x *alfredLoadImageClient) Send(m *LoadImageMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *alfredLoadImageClient) Recv() (*LoadImageResponse, error) {
	m := new(LoadImageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *alfredClient) ScheduleJob(ctx context.Context, in *ScheduleJobRequest, opts ...grpc.CallOption) (*ScheduleJobResponse, error) {
	out := new(ScheduleJobResponse)
	err := c.cc.Invoke(ctx, Alfred_ScheduleJob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alfredClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, Alfred_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlfredServer is the server API for Alfred service.
// All implementations must embed UnimplementedAlfredServer
// for forward compatibility
type AlfredServer interface {
	LoadImage(Alfred_LoadImageServer) error
	ScheduleJob(context.Context, *ScheduleJobRequest) (*ScheduleJobResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedAlfredServer()
}

// UnimplementedAlfredServer must be embedded to have forward compatible implementations.
type UnimplementedAlfredServer struct {
}

func (UnimplementedAlfredServer) LoadImage(Alfred_LoadImageServer) error {
	return status.Errorf(codes.Unimplemented, "method LoadImage not implemented")
}
func (UnimplementedAlfredServer) ScheduleJob(context.Context, *ScheduleJobRequest) (*ScheduleJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScheduleJob not implemented")
}
func (UnimplementedAlfredServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAlfredServer) mustEmbedUnimplementedAlfredServer() {}

// UnsafeAlfredServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlfredServer will
// result in compilation errors.
type UnsafeAlfredServer interface {
	mustEmbedUnimplementedAlfredServer()
}

func RegisterAlfredServer(s grpc.ServiceRegistrar, srv AlfredServer) {
	s.RegisterService(&Alfred_ServiceDesc, srv)
}

func _Alfred_LoadImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AlfredServer).LoadImage(&alfredLoadImageServer{stream})
}

type Alfred_LoadImageServer interface {
	Send(*LoadImageResponse) error
	Recv() (*LoadImageMessage, error)
	grpc.ServerStream
}

type alfredLoadImageServer struct {
	grpc.ServerStream
}

func (x *alfredLoadImageServer) Send(m *LoadImageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *alfredLoadImageServer) Recv() (*LoadImageMessage, error) {
	m := new(LoadImageMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Alfred_ScheduleJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlfredServer).ScheduleJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Alfred_ScheduleJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlfredServer).ScheduleJob(ctx, req.(*ScheduleJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alfred_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlfredServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Alfred_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlfredServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Alfred_ServiceDesc is the grpc.ServiceDesc for Alfred service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Alfred_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Alfred",
	HandlerType: (*AlfredServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScheduleJob",
			Handler:    _Alfred_ScheduleJob_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Alfred_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LoadImage",
			Handler:       _Alfred_LoadImage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/alfred.proto",
}
